# Generated by Django 4.2.2 on 2023-08-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_customerorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
    ]
