# Generated by Django 4.2.2 on 2023-06-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('discounted_price', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('T', 'Tools'), ('A', 'Agriculture'), ('W', 'Weapones'), ('U', 'Utensils')], max_length=1)),
                ('product_image', models.ImageField(upload_to='static/image/')),
            ],
        ),
    ]
