# Generated by Django 4.2.2 on 2023-06-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('discount', models.FloatField()),
                ('category', models.CharField(choices=[('T', 'Tools'), ('A', 'Agriculture'), ('W', 'Weapones'), ('U', 'Utensils')], max_length=1)),
                ('image', models.ImageField(upload_to='static/image/')),
            ],
        ),
    ]
