# Generated by Django 4.2.2 on 2023-06-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tools',
            new_name='service',
        ),
    ]
