# Generated by Django 4.2.2 on 2023-06-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_tools_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discounted_price',
            field=models.FloatField(default=0),
        ),
    ]
