# Generated by Django 4.2.2 on 2023-06-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='discounted_price',
        ),
    ]
